-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.cart DROP CONSTRAINT IF EXISTS cart_user_id_fkey;

ALTER TABLE IF EXISTS public.cart_item DROP CONSTRAINT IF EXISTS cart_item_cart_id_fkey;

ALTER TABLE IF EXISTS public.cart_item DROP CONSTRAINT IF EXISTS fkjcyd5wv4igqnw413rgxbfu4nv;

ALTER TABLE IF EXISTS public.color DROP CONSTRAINT IF EXISTS color_product_id_fkey;

ALTER TABLE IF EXISTS public.images DROP CONSTRAINT IF EXISTS fk8sfun6tj1hqb85ed52o8mkqyh;

ALTER TABLE IF EXISTS public.product DROP CONSTRAINT IF EXISTS product_category_id_fkey;

ALTER TABLE IF EXISTS public.size DROP CONSTRAINT IF EXISTS size_product_id_fkey;

ALTER TABLE IF EXISTS public.social_account DROP CONSTRAINT IF EXISTS social_account_users_id_fkey;

ALTER TABLE IF EXISTS public.tokens DROP CONSTRAINT IF EXISTS tokens_user_id_fkey;

ALTER TABLE IF EXISTS public.users DROP CONSTRAINT IF EXISTS fk_users_role;

ALTER TABLE IF EXISTS public.users DROP CONSTRAINT IF EXISTS fkqmifheg6lnigfifvlmpjnuny8;



DROP TABLE IF EXISTS public.cart;

CREATE TABLE IF NOT EXISTS public.cart
(
    id bigserial NOT NULL,
    user_id bigint,
    CONSTRAINT cart_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.cart_item;

CREATE TABLE IF NOT EXISTS public.cart_item
(
    id bigint NOT NULL DEFAULT nextval('"cart_item _id_seq"'::regclass),
    quantity integer NOT NULL,
    size character varying(255) COLLATE pg_catalog."default",
    cart_id bigint,
    product_id bigint,
    color character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT "cart_item _pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.category;

CREATE TABLE IF NOT EXISTS public.category
(
    id bigserial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT category_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.color;

CREATE TABLE IF NOT EXISTS public.color
(
    id bigserial NOT NULL,
    color character varying(255) COLLATE pg_catalog."default" NOT NULL,
    product_id bigint,
    CONSTRAINT color_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.images;

CREATE TABLE IF NOT EXISTS public.images
(
    id bigserial NOT NULL,
    image_url character varying(255) COLLATE pg_catalog."default",
    product_id bigint,
    CONSTRAINT images_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.product;

CREATE TABLE IF NOT EXISTS public.product
(
    id bigserial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    price double precision NOT NULL,
    discount integer,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    category_id bigint,
    s_price double precision NOT NULL,
    CONSTRAINT product_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.role;

CREATE TABLE IF NOT EXISTS public.role
(
    id bigserial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT USER,
    CONSTRAINT role_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.size;

CREATE TABLE IF NOT EXISTS public.size
(
    id bigserial NOT NULL,
    size character varying(255) COLLATE pg_catalog."default",
    product_id bigint,
    CONSTRAINT size_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.social_account;

CREATE TABLE IF NOT EXISTS public.social_account
(
    id bigserial NOT NULL,
    provider character varying(255) COLLATE pg_catalog."default",
    provider_id character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    users_id bigint,
    CONSTRAINT social_account_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.tokens;

CREATE TABLE IF NOT EXISTS public.tokens
(
    id bigserial NOT NULL,
    token character varying(255) COLLATE pg_catalog."default",
    refresh_token character varying(255) COLLATE pg_catalog."default",
    "tokenType" character varying(50) COLLATE pg_catalog."default",
    is_mobile boolean,
    user_id bigint,
    expired boolean NOT NULL,
    revoked boolean NOT NULL,
    token_type character varying(50) COLLATE pg_catalog."default",
    expiration_date timestamp without time zone,
    refresh_expiration_date timestamp without time zone,
    CONSTRAINT tokens_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id bigserial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    google_account_id integer DEFAULT 0,
    role_id bigint DEFAULT 2,
    created_at timestamp without time zone,
    email character varying(255) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    address character varying(255) COLLATE pg_catalog."default",
    cart_id bigint,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.cart
    ADD CONSTRAINT cart_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cart_item
    ADD CONSTRAINT cart_item_cart_id_fkey FOREIGN KEY (cart_id)
    REFERENCES public.cart (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.cart_item
    ADD CONSTRAINT fkjcyd5wv4igqnw413rgxbfu4nv FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.color
    ADD CONSTRAINT color_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.images
    ADD CONSTRAINT fk8sfun6tj1hqb85ed52o8mkqyh FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT product_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.size
    ADD CONSTRAINT size_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.social_account
    ADD CONSTRAINT social_account_users_id_fkey FOREIGN KEY (users_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tokens
    ADD CONSTRAINT tokens_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT fk_users_role FOREIGN KEY (role_id)
    REFERENCES public.role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT fkqmifheg6lnigfifvlmpjnuny8 FOREIGN KEY (cart_id)
    REFERENCES public.cart (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;